{{- if .Values.vscode.ingress.enabled -}}
{{- $fullName := include "devmode.fullname" . -}}
{{- $svcPort := .Values.vscode.service.port -}}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "devmode.labels" . | nindent 4 }}
    #labels: "code-server"
  {{- with .Values.vscode.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.vscode.ingress.ingressClassName }}
  ingressClassName: {{ .Values.vscode.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.vscode.ingress.tls }}
  tls:
    {{- range .Values.vscode.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
    {{- range .Values.vscode.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- else -}}
    {{- range .Values.vscode.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
