{{- if not .Values.vscode.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    {{- include "devmode.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | default "vran" }}
type: Opaque
data:
  {{- if .Values.vscode.password }}
  password: "{{ .Values.vscode.password | b64enc }}"
  {{- else }}
  password: "{{ randAlphaNum 24 | b64enc }}"
  {{- end }}
{{- end }}
